{% set name = "wildmeshing" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/wildmeshing/wildmeshing-python/archive/{{ version }}.tar.gz
    sha256: 7350de9c8704457157402c4d18f335eec015989db6aba2d5bf0d15192b3fb550
  - url: https://github.com/teseoch/svgpathtools/archive/1.4.tar.gz
    sha256: 9e3548d3312241b09cd595dca3e23c2a3c54dfee8439d29d9e6b46ca4c773d1b
    folder: svgpathtools

build:
  number: 0
  skip: True  # [py<31]
  script:
    - mv svgpathtools/* wildmeshing/parse_svg
    - ls wildmeshing/parse_svg
    - rm -r svgpathtools
    - set "CMAKE_GENERATOR=NMake Makefiles"  # [win]
    - {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - python
    - pip
    - libblas
    - libcblas
    - numpy
    - gmp     # [unix]
    - mpir    # [win]
  run:
    - python
    - mpir    # [win]
    - {{ pin_compatible('numpy') }}
    - svgwrite

test:
  imports:
    - wildmeshing

about:
  home: https://github.com/wildmeshing/wildmeshing-python
  license: LGPL
  license_family: LGPL
  license_file: LICENSE
  summary: 'Simple, fast, robust meshing'

  description: 'Simple, fast, robust meshing'
  doc_url: https://github.com/wildmeshing/wildmeshing-python
  dev_url: https://github.com/wildmeshing/wildmeshing-python

extra:
  recipe-maintainers:
    - teseoch
    - Yixin-Hu
